export const SET_CURRENCIES = 'SET_CURRENCIES';
export const SET_SEND_CURRENCY = 'SET_SEND_CURRENCY';
export const SET_SEND_COUNT = 'SET_SEND_COUNT';
export const SET_RECEIVE_CURRENCY = 'SET_RECEIVE_CURRENCY';
export const SET_RECEIVE_COUNT = 'SET_RECEIVE_COUNT';
export const SET_MIN_COUNT = 'SET_MIN_COUNT';
